name=ZynthLib
version=0.0.4
author=MLE Tech
maintainer=Markeby mle@markeby.net
sentence=Zynthesiser library files for core functions
paragraph=Currently supporting ESP32
category=Other
architectures=esp32
url=https://github.com/markeby/ZynthLib
includes=Debug.h,ZynthTime.h,Envelope.h,I2Cdevices.h,SoftLFO.h
